# Social-LSTM

In [22]:
from tensorboard.backend.event_processing import event_accumulator
import pandas as pd

# 加载events文件
ea = event_accumulator.EventAccumulator('runs_social_lstm')
ea.Reload()

all_data = {}
for tag in ea.Tags()['scalars']:
    data = ea.Scalars(tag)
    all_data[tag] = {item.step: item.value for item in data}

df = pd.DataFrame(all_data)
df.index.name = 'step'

In [23]:
df = df[(df.index % 10) ==0]

In [24]:
df

,loss/bc_loss,Metric/P_X_MAE,Metric/P_Y_MAE,Metric/P_X_HD,Metric/P_Y_HD,Metric/V_X_MAE,Metric/V_Y_MAE,Metric/V_X_HD,Metric/V_Y_HD,score/score,loss/seq_loss
step,,,,,,,,,,,
0,0.044084,0.760136,0.720265,1.321000,1.522604,0.447538,0.465617,0.677539,0.729699,37.0,NaN
10,0.018640,0.883514,0.626151,1.583362,1.125534,0.513495,0.389389,0.795217,0.549263,16.0,NaN
20,0.009092,0.747985,0.791538,1.264838,1.427844,0.440630,0.485166,0.646267,0.758035,NaN,NaN
30,0.015624,0.738063,0.826194,1.315852,1.547596,0.446348,0.514610,0.658989,0.838355,10.0,NaN
40,0.620532,0.563438,0.930505,0.727879,1.644274,0.293213,0.547178,0.154102,0.679257,NaN,0.407873
...,...,...,...,...,...,...,...,...,...,...,...
15970,0.366537,0.541147,0.613339,0.717618,0.842366,0.293662,0.348449,0.133904,0.236887,13.0,0.010309
15980,0.408350,0.573442,0.612614,0.833913,0.849887,0.324519,0.354028,0.201895,0.251821,NaN,0.010118
15990,0.800712,0.569036,0.621783,0.772281,0.846022,0.310720,0.356659,0.165582,0.248397,20.0,0.016484
16000,0.427367,0.556104,0.587974,0.741288,0.762257,0.299958,0.332818,0.145034,0.201643,NaN,0.013459
16010,0.374814,0.549797,0.604545,0.709030,0.789558,0.290150,0.338926,0.124301,0.214665,16.0,0.010952

# GAIL

In [37]:
from tensorboard.backend.event_processing import event_accumulator
import pandas as pd

# 加载events文件
ea = event_accumulator.EventAccumulator('runs_gail_base')
ea.Reload()

all_data = {}
for tag in ea.Tags()['scalars']:
    data = ea.Scalars(tag)
    all_data[tag] = {item.step: item.value for item in data}

df = pd.DataFrame(all_data)
df.index.name = 'step'

In [38]:
df = df[(df.index % 10) ==0]

In [39]:
df.sort_values(by='Metric/P_X_MAE')

,Metric/P_X_MAE,Metric/P_Y_MAE,Metric/P_X_HD,Metric/P_Y_HD,Metric/V_X_MAE,Metric/V_Y_MAE,Metric/V_X_HD,Metric/V_Y_HD,score/score,score/discriminator,loss/discriminator_loss,loss/expert_acc,loss/learner_acc,loss/q_1,loss/q_2,loss/actor_loss,loss/q_for_actor,loss/alpha
step,,,,,,,,,,,,,,,,,,
140,0.820783,1.078276,1.243387,1.761993,0.481827,0.652438,0.566804,0.861531,47.0,100.795883,0.733323,0.828125,0.937500,0.079270,0.078431,-2.833914,2.782504,0.132363
120,0.821691,1.020164,1.291337,1.678161,0.495083,0.621419,0.589382,0.813579,16.0,18.856560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,0.860969,1.165231,1.374689,2.065694,0.506628,0.702812,0.593776,0.983416,22.0,73.810005,0.927309,0.750000,0.843750,0.110113,0.110129,-2.877156,2.810147,0.181187
11350,0.871707,0.953837,1.049830,1.649177,0.518400,0.566237,0.663658,0.727001,10.0,1.729372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11340,0.874993,0.952747,1.034458,1.652292,0.518081,0.565597,0.666617,0.728305,26.0,4.630437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,2.682139,2.659114,6.215186,6.130374,1.624274,1.608235,2.761498,2.676337,21.0,18.623966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,2.780140,2.400441,6.480809,5.447366,1.678913,1.462388,2.866974,2.411283,14.0,21.518518,0.643166,0.828125,0.906250,0.121585,0.128200,-3.362540,3.384316,0.001528
280,2.804122,2.468999,6.523828,5.635908,1.687594,1.500783,2.856683,2.504072,24.0,69.313469,0.566371,0.875000,0.890625,0.206542,0.205292,-3.849289,3.877055,-0.004589
260,2.886112,2.101608,6.779331,4.546275,1.742500,1.277787,2.986018,2.049310,14.0,26.896429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,2.996729,1.832217,7.061700,3.671542,1.807855,1.103049,3.101147,1.754177,17.0,42.914261,0.835576,0.875000,0.812500,0.190776,0.231213,-3.318653,3.334186,-0.000437

# MentIRL

In [34]:
from tensorboard.backend.event_processing import event_accumulator
import pandas as pd

# 加载events文件
ea = event_accumulator.EventAccumulator('runs_maxent_irl')
ea.Reload()

all_data = {}
for tag in ea.Tags()['scalars']:
    data = ea.Scalars(tag)
    all_data[tag] = {item.step: item.value for item in data}

df = pd.DataFrame(all_data)
df.index.name = 'step'

In [35]:
df = df[(df.index % 10) ==0]

In [36]:
df.sort_values(by='Metric/P_X_MAE')

,Metric/P_X_MAE,Metric/P_Y_MAE,Metric/P_X_HD,Metric/P_Y_HD,Metric/V_X_MAE,Metric/V_Y_MAE,Metric/V_X_HD,Metric/V_Y_HD,score/score,score/irl_reward,loss/maxent_total_loss,loss/expert_reward_mean,loss/agent_reward_mean,loss/reward_diff,loss/q_1,loss/q_2,loss/actor_loss,loss/q_for_actor,loss/alpha
step,,,,,,,,,,,,,,,,,,,
120,0.818815,0.859070,1.273426,1.292587,0.494784,0.522176,0.590551,0.614595,16.0,-2.913212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,0.837468,0.952836,1.278769,1.562008,0.489490,0.588267,0.583142,0.744321,47.0,-0.300011,-31.775154,3.296593e+01,-5.328403,3.829434e+01,0.043481,0.042934,1.580608,-1.630431,0.128430
130,0.853542,0.885295,1.323465,1.384495,0.501568,0.534704,0.590513,0.651391,22.0,3.275469,-19.167183,1.864389e+01,-7.701233,2.634512e+01,0.068076,0.071646,1.825336,-1.898242,0.185082
90,0.871757,0.890624,1.359685,1.336521,0.517567,0.534386,0.625256,0.636207,10.0,62.483032,-12.130951,1.843546e+01,-0.855574,1.929103e+01,0.087266,0.084451,1.163076,-1.324771,0.414830
150,0.878551,1.279759,1.438337,2.414016,0.507633,0.780569,0.607178,1.142448,13.0,0.298148,-25.419304,3.330758e+01,-0.988646,3.429623e+01,0.045433,0.046793,2.007980,-2.031165,0.070723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,2.964868,2.622148,7.058378,5.966139,1.804665,1.582448,3.065291,2.609553,26.0,-6.888844,43986.960938,3.778361e+04,1245.289185,3.653832e+04,0.030739,0.031393,2.678647,-2.666131,-0.000126
1110,2.966008,2.549726,7.079314,5.703660,1.808581,1.536314,3.082705,2.465934,40.0,-13.305428,-45140.042969,7.173679e+04,255.071579,7.148172e+04,0.019839,0.021962,2.985652,-2.974679,-0.000986
1250,2.986584,2.623671,7.107172,5.831949,1.819237,1.578471,3.086329,2.533208,12.0,-3.623517,50177.230469,4.407978e+04,1309.366821,4.277041e+04,0.021564,0.027412,2.925516,-2.913550,-0.000900
1120,2.992629,2.548677,7.137591,5.683330,1.821392,1.540518,3.102677,2.472196,9.0,-2.720021,-62296.777344,1.053631e+05,629.663818,1.047334e+05,0.044028,0.035792,2.623829,-2.612342,-0.002155
6110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10096.218750,1.174280e+07,117339.460938,1.162546e+07,0.005723,0.005753,3.224032,-3.211761,0.000936